[general]
import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[window]
padding = { x = 10, y = 10 }
opacity = 0.95
blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "regular" }
size = 15
