
backend = "glx";
vsync = true;

corner-radius = 20;
detect-rounded-corners = true;

blur-background = true;
blur-background-frame = true;
blur:
{
  method = "dual_kawase";
  strength = 5;
};
blur-background-exclude = [
    "class_g = 'slop'",
];

inactive-opacity = 0.95;
active-opacity = 0.97;
detect-client-opacity = true;
opacity-rule = [
  "100:class_g = 'firefox-esr'",
  "100:class_g = 'zen'",
  "100:class_g = 'maim'",
  "85:class_g = 'code'",
  "100:class_g = 'vesktop'",
  "60:class_g = 'Joplin'"
];

rounded-corners-exclude = [
  "class_g = 'Rofi'",
  "class_g = 'Dunst'",
  "class_g = 'Polybar'"
];

shadow = true;
shadow-radius = 20
shadow-opacity = .75
shadow-offset-x = -15
shadow-exclude = [
  "class_g = 'Polybar'",
  "name = 'polybar'"
];
