[colors]
base = #1e1e2e
mantle = #181825
crust = #11111b
text = #cdd6f4
subtext0 = #a6adc8
subtext1 = #bac2de
surface0 = #313244
surface1 = #45475a
surface2 = #585b70
overlay0 = #6c7086
overlay1 = #7f849c
overlay2 = #9399b2
blue = #89b4fa
lavender = #b4befe
sapphire = #74c7ec
sky = #89dceb
teal = #94e2d5
green = #a6e3a1
yellow = #f9e2af
peach = #fab387
maroon = #eba0ac
red = #f38ba8
mauve = #cba6f7
pink = #f5c2e7
flamingo = #f2cdcd
rosewater = #f5e0dc
transparent = #FF00000

;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = ${colors.base}
background-alt = ${colors.blue}
foreground = ${colors.text}
primary = ${colors.mauve}
secondary = ${colors.mantle}
alert = ${colors.red}
disabled = ${colors.subtext1}

[bar/main2]
monitor = DP-1
width = 100%
height = 45px

radius = 0
radius-top-left = 18
radius-bottom-left = 18

background = ${colors.background}
foreground = ${colors.foreground}

#offset-y = 40%
#offset-y = 10px
line-size = 4px

border-top-size = 20px
border-left-size = 340px
border-right-size = 0px
border-bottom-size = 0px
border-color = #00000000

padding-left = 2
padding-right = 1

module-margin = 0

font-0 = JetBrainsMonoNerd Font Mono:size=12;4
font-1 = JetBrainsMonoNerd Font Mono:size=16;4
font-2 = JetBrainsMonoNerd Font Mono:size=18;4
modules-left = debian space date
modules-center = xworkspaces
modules-right = pomodoro space sep space stopwatch space sep space timer space
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
wm-restack = i3

#override-redirect = true
;

[bar/main]
monitor = HDMI-2
width = 100%
height = 45px

radius = 0
radius-top-right = 18
radius-bottom-right = 18

background = ${colors.background}
foreground = ${colors.foreground}

#offset-y = 40%
#offset-y = 10px
line-size = 4px

border-top-size = 20px
border-left-size = 0px
border-right-size = 340px
border-bottom-size = 0px
border-color = #00000000

padding-left = 2
padding-right = 1

module-margin = 0

font-0 = JetBrainsMonoNerd Font Mono:size=12;4
font-1 = JetBrainsMonoNerd Font Mono:size=16;4
font-2 = JetBrainsMonoNerd Font Mono:size=18;4
modules-left = tray
modules-center = cava space music
modules-right = pulseaudio powermenu space
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
wm-restack = i3

#override-redirect = true
;

[module/pomodoro]
type = custom/script
exec = python3 ~/.config/polybar/scripts/pomodoro/pomodoro.py
click-left = python3 ~/.config/polybar/scripts/pomodoro/pomodoro.py toggle
click-middle = python3 ~/.config/polybar/scripts/pomodoro/pomodoro.py reset
click-right = python3 ~/.config/polybar/scripts/pomodoro/pomodoro.py skip
tail = true

[module/stopwatch]
type = custom/script
exec = python3 ~/.config/polybar/scripts/pomodoro/stopwatch.py
click-left = python3 ~/.config/polybar/scripts/pomodoro/stopwatch.py toggle
click-right = python3 ~/.config/polybar/scripts/pomodoro/stopwatch.py reset
tail = true
interval = 1

[module/timer]
type = custom/script
exec = python3 ~/.config/polybar/scripts/pomodoro/timer.py
click-left = ~/.config/polybar/scripts/pomodoro/timer.py start
click-right = ~/.config/polybar/scripts/pomodoro/timer.py add
click-middle = ~/.config/polybar/scripts/pomodoro/timer.py reset
tail = true
interval = 1
label = %output%


[module/tray]
type = internal/tray
tray-size = 40%
format-margin = 8px
tray-spacing = 8px

[module/powermenu]
type = custom/menu

expand-right = true

format-spacing = 1

label-open = %{T2}%{T-}
label-open-foreground = ${colors.text}
label-close =  cancel
label-close-foreground = ${colors.maroon}
label-separator = |
label-separator-foreground = ${colors.subtext1}

;Powermenu
menu-0-0 = "reboot "
menu-0-0-exec = systemctl reboot
menu-0-0-foreground = ${colors.red}

menu-0-1 = "power off"
menu-0-1-exec = systemctl poweroff
menu-0-1-foreground = ${colors.red}

menu-0-2 = "hibernate"
menu-0-2-exec = systemctl hibernate
menu-0-2-foreground = ${colors.red}

[module/xworkspaces]
type = internal/xworkspaces

label-active = %{T3}%{T-}
label-active-padding = 1
label-active-foreground = ${colors.lavender}
label-active-font = 1

label-occupied = %{T2}󰄰%{T-}
label-occupied-padding = 1
label-occupied-font = 1

label-empty = %{T2}󰄰%{T-}
label-empty-background = ${colors.base}
label-empty-padding = 1
label-empty-font = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/music]
type = custom/script
exec = playerctl metadata --format "{{ title }}"
interval = 2

[module/pulseaudio]
type = internal/pulseaudio


#format-volume-prefix = %{T2}󰕾 %{T-}
format-volume-foreground = ${colors.text}
format-volume-prefix-foreground = ${colors.subtext0}
format-volume = <label-volume>
label-volume = %percentage%% %{T2}󰕾 %{T-}

label-muted = %percentage%% %{T2}󰖁%{T-}
label-muted-foreground = ${colors.surface0}

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless

interval = 1
format-connected-prefix-foreground = ${colors.white}
format-connected-foreground = ${colors.white}
format-connected = <label-connected>
label-connected = 󰖩
label-connected-padding = 0

format-disconnected = <label-disconnected>
format-disconnected-padding = 0
label-disconnected = 󰖪
label-disconnected-foreground = ${colors.white}
label-disconnected-padding = 0

[module/date]
type = internal/date
interval = 1

date = %H:%M - %d %B
date-alt = %Y-%m-%d %H:%M:%S

label = %date%
label-foreground = ${colors.lavender}

[module/debian]
type = custom/text
content = %{T2}%{T-}
content-foreground = ${colors.mauve}
content-margin = 0

[module/sep]
type = custom/text
content = %{T2}-%{T-}
content-foreground = ${colors.lavender}
content-margin = 0

[module/mus]
type = custom/text
content = %{T3}󰝚%{T-}
content-foreground = ${colors.green}
content-margin = 0

[module/space]
type = custom/text
content = " "

[module/cava]
type = custom/script
exec = ~/.config/polybar/scripts/cava.py --source alsa_input.usb-Razer_Inc_Razer_Seiren_Mini_UC2315L03207956-00.mono-fallback -f 30 -e cdd6f4,cdd6f4,cdd6f4,cdd6f4 -b 6 -c average
tail = true

[settings]
screenchange-reload = true
pseudo-transparency = true
